version: '2'
services:
    jhipstertest-app:
        image: jhipstertest
        external_links:
            - jhipstertest-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/jhipstertest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstertest-postgresql:
        extends:
            file: postgresql.yml
            service: jhipstertest-postgresql
